version: '3.2'
services:
  nginx:
    image: nginx:1.15.8-alpine
    expose:
      - 443
    depends_on:
      - php
    environment:
      DOMAIN_NAME: default:${DOMAIN_DEFAULT}
    volumes:
      - ./docker/nginx/certs:/etc/nginx/certs:ro
      - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf:ro
      - ./public/:/srv/public/:ro
  php:
    build: ./docker/php
    environment:
      PHP_IDE_CONFIG: serverName=${XDEBUG_SERVER_NAME}
      XDEBUG_CONFIG: remote_host=${LOCAL_IP} remote_port=${XDEBUG_PORT} idekey=${XDEBUG_IDEKEY}
    volumes:
      - ~/.composer:/home/.composer
      - ./docker/config/bashrc:/home/.bashrc
      - ./docker/config/bash_aliases:/home/.bash_aliases
      - ./docker/config/inputrc:/home/.inputrc
      - ./docker/data/history:/home/.bash_history
      - ./:/srv/
  postgres:
    image: postgres:10.6-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: arche-api
      POSTGRES_USER: arche-api
      POSTGRES_DB: arche-api
    volumes:
      - postgres:/data
volumes:
  postgres: ~